# users/publications_data.py
#
# Single source of truth for Le Bin Ho / Quantar Lab's publication list, used by:
#   - the 4 "research direction" pages (views.research_metrology / _algorithms /
#     _foundations / _simulation), which filter PUBLICATIONS by `category` and
#     render the matches server-side;
#   - kept in sync (manually, when the list changes) with the embedded JSON in
#     users/templates/publication.html, which is the full unfiltered list shown
#     on the /publication/ page.
#
# category is one of: "algorithms", "metrology", "foundations", "simulation",
# or None for older (pre-quantum-computing) papers that don't fit any of the
# four current research directions.

PUBLICATIONS = [
    {"fy": 2026, "type": "peer", "title": "Trade-off relation between integrated metrological gain and local dissipation in magnetic-field sensing by quantum spin ensemble", "authors": "Nozomu Takahashi, Le Bin Ho, Hiroaki Matsueda", "venue": "Advanced Quantum Technologies 9, e70376 (2026)", "year": 2026, "link": "https://advanced.onlinelibrary.wiley.com/doi/10.1002/qute.70376", "category": "metrology"},
    {"fy": 2026, "type": "peer", "title": "Flexible genetic algorithm for quantum support vector machines", "authors": "Nguyen Minh Duc, Vu Tuan Hai, Le Bin Ho, Lan Nguyen Tran", "venue": "Machine Learning: Science and Technology 7, 045030 (2026)", "year": 2026, "link": "https://iopscience.iop.org/article/10.1088/2632-2153/ae894c", "category": "algorithms"},
    {"fy": 2026, "type": "peer", "title": "Feedback-based quantum control for safe and synergistic drug combination design", "authors": "Mai Nguyen Phuong Nhi, Lan Nguyen Tran, Le Bin Ho", "venue": "Journal of Computational Science 100, 102965 (2026)", "year": 2026, "link": "https://www.sciencedirect.com/science/article/pii/S1877750326001833", "category": "algorithms"},
    {"fy": 2026, "type": "peer", "title": "Exact gradient for general cost functions in variational quantum algorithms", "authors": "Jesus Urbaneja, Le Bin Ho", "venue": "Physical Review A 113, 042435 (2026)", "year": 2026, "link": "https://journals.aps.org/pra/abstract/10.1103/6s2c-mxgx", "category": "algorithms"},
    {"fy": 2026, "type": "peer", "title": "Quantum simulation of strong charge-parity violation and the Peccei-Quinn mechanism", "authors": "Le Bin Ho", "venue": "Physical Review D 113, 074507 (2026)", "year": 2026, "link": "https://journals.aps.org/prd/abstract/10.1103/yx1t-mkgp", "category": "simulation"},
    {"fy": 2026, "type": "peer", "title": "Advancing quantum process tomography through quantum compilation", "authors": "Huynh Le Dan Linh, Vu Tuan Hai, Le Bin Ho", "venue": "Advanced Quantum Technologies 9, e00494 (2026)", "year": 2026, "link": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/qute.202500494", "category": "algorithms"},
    {"fy": 2026, "type": "preprint", "title": "Benchmarking loss functions for trainable quantum feature maps", "authors": "Nguyen Dinh Quyen, Vu Tuan Hai, Nguyen Quoc Chuong, Le Bin Ho, Lan Nguyen Tran", "venue": "arXiv:2607.12487", "year": 2026, "link": "https://arxiv.org/abs/2607.12487", "category": "algorithms"},
    {"fy": 2026, "type": "preprint", "title": "Measurement geometry as a resource for certifying network nonlocality", "authors": "Leon Adachi, Le Bin Ho", "venue": "arXiv:2607.04656", "year": 2026, "link": "https://arxiv.org/abs/2607.04656", "category": "foundations"},
    {"fy": 2026, "type": "preprint", "title": "Towards automated selection of quantum encoding circuits via meta-learning", "authors": "Dao Duy Tung, Nguyen Quoc Chuong, Vu Tuan Hai, Le Bin Ho, Lan Nguyen Tran", "venue": "arXiv:2604.19076", "year": 2026, "link": "https://arxiv.org/abs/2604.19076", "category": "algorithms"},
    {"fy": 2026, "type": "preprint", "title": "Interference-induced state engineering and Hamiltonian control for noisy collective-spin metrology", "authors": "Le Bin Ho, Vu Xuan Tung Duong, Nozomu Takahashi, Hiroaki Matsueda", "venue": "arXiv:2603.22734", "year": 2026, "link": "https://arxiv.org/abs/2603.22734", "category": "metrology"},
    {"fy": 2026, "type": "preprint", "title": "Boosting the performance of a Lipkin-Meshkov-Glick quantum battery via symmetry-breaking quenches and bosonic baths", "authors": "Le Bin Ho, Duc Tuan Hoang, Tran Duong Anh-Tai, Thomas Busch, Thomas Fogarty", "venue": "arXiv:2602.17121", "year": 2026, "link": "https://arxiv.org/abs/2602.17121", "category": "simulation"},
    {"fy": 2025, "type": "peer", "title": "Optimized quantum sensor networks for ultralight dark matter detection", "authors": "Adriel I. Santoso, Le Bin Ho", "venue": "Physical Review D 112, L081301 (2025)", "year": 2025, "link": "https://journals.aps.org/prd/abstract/10.1103/rv43-54zq", "category": "metrology"},
    {"fy": 2025, "type": "peer", "title": "Two-time approach to past-future quantum dynamics: formalism and applications", "authors": "Le Bin Ho", "venue": "Advanced Physics Research, e00099 (2025)", "year": 2025, "link": "https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/apxr.202500099", "category": "foundations"},
    {"fy": 2025, "type": "peer", "title": "Entangled state preparation via cluster states on quantum computers with <qo|op> software", "authors": "Vu Tuan Hai, Jesus Urbaneja, Le Bin Ho", "venue": "2025 IEEE International Conference on Quantum Software (QSW), 116-122 (2025)", "year": 2025, "link": "https://ieeexplore.ieee.org/abstract/document/11134319", "category": "algorithms"},
    {"fy": 2025, "type": "peer", "title": "Detecting and protecting entanglement through nonlocality, variational entanglement witness, and nonlocal measurements", "authors": "Haruki Matsunaga, Le Bin Ho", "venue": "Physical Review Research 7, 013239 (2025)", "year": 2025, "link": "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.7.013239", "category": "foundations"},
    {"fy": 2025, "type": "preprint", "title": "Imaginary-time-enhanced feedback-based quantum algorithms for universal ground-state preparation", "authors": "Thanh Nguyen Van Long, Lan Nguyen Tran, Le Bin Ho", "venue": "arXiv:2512.13044", "year": 2025, "link": "https://arxiv.org/abs/2512.13044", "category": "simulation"},
    {"fy": 2025, "type": "preprint", "title": "Statistical analysis of barren plateaus in variational quantum algorithms", "authors": "Le Bin Ho, Jesus Urbaneja, Sahel Ashhab", "venue": "arXiv:2508.08915", "year": 2025, "link": "https://arxiv.org/abs/2508.08915", "category": "algorithms"},
    {"fy": 2024, "type": "peer", "title": "Multi-target quantum compilation algorithm", "authors": "Vu Tuan Hai, Nguyen Tan Viet, Jesus Urbaneja, Nguyen Vu Linh, Lan Nguyen Tran, Le Bin Ho", "venue": "Machine Learning: Science and Technology 5, 045057 (2024)", "year": 2024, "link": "https://iopscience.iop.org/article/10.1088/2632-2153/ad9705", "category": "algorithms"},
    {"fy": 2024, "type": "peer", "title": "Squeezing-induced quantum-enhanced multiphase estimation", "authors": "Le Bin Ho", "venue": "Physical Review Research 6, 033292 (2024)", "year": 2024, "link": "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.6.033292", "category": "metrology"},
    {"fy": 2024, "type": "peer", "title": "Harnessing graph state resources for robust quantum magnetometry under noise", "authors": "Phu Trong Nguyen, Trung Kien Le, Hung Q. Nguyen, Le Bin Ho", "venue": "Scientific Reports 14, 20528 (2024)", "year": 2024, "link": "https://www.nature.com/articles/s41598-024-71365-8", "category": "metrology"},
    {"fy": 2024, "type": "peer", "title": "Quantum battery optimization through quantum machine learning techniques", "authors": "Vu Tuan Hai, Vo Minh Kiet, Le Vu Trung Duong, Pham Hoai Luan, Le Bin Ho, Yasuhiko Nakashima", "venue": "2024 21st International SoC Design Conference (ISOCC), 121-122 (2024)", "year": 2024, "link": "https://ieeexplore.ieee.org/document/10762673", "category": "simulation"},
    {"fy": 2024, "type": "peer", "title": "<qo|op>: a quantum object optimizer", "authors": "Vu Tuan Hai, Nguyen Tan Viet, Le Bin Ho", "venue": "SoftwareX 26, 101726 (2024)", "year": 2024, "link": "https://doi.org/10.1016/j.softx.2024.101726", "category": "algorithms"},
    {"fy": 2023, "type": "peer", "title": "Variational quantum metrology for multiparameter estimation under dephasing noise", "authors": "Trung Kien Le, Hung Q. Nguyen, Le Bin Ho", "venue": "Scientific Reports 13, 17775 (2023)", "year": 2023, "link": "https://www.nature.com/articles/s41598-023-44786-0", "category": "metrology"},
    {"fy": 2023, "type": "peer", "title": "A stochastic evaluation of quantum Fisher information matrix with generic Hamiltonians", "authors": "Le Bin Ho", "venue": "EPJ Quantum Technology 10, 37 (2023)", "year": 2023, "link": "https://epjquantumtechnology.springeropen.com/articles/10.1140/epjqt/s40507-023-00195-w", "category": "metrology"},
    {"fy": 2023, "type": "peer", "title": "Quantum backaction effects in sequential measurements", "authors": "Le Bin Ho", "venue": "Annals of Physics 453, 169310 (2023)", "year": 2023, "link": "https://www.sciencedirect.com/science/article/pii/S0003491623000969", "category": "foundations"},
    {"fy": 2023, "type": "peer", "title": "Increased success probability in Hardy's nonlocality: theory and demonstration", "authors": "Duc Minh Tran, Van-Duy Nguyen, Le Bin Ho, Hung Q. Nguyen", "venue": "Physical Review A 107, 042210 (2023)", "year": 2023, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.107.042210", "category": "foundations"},
    {"fy": 2023, "type": "peer", "title": "No-go result for quantum postselection measurements of a rank-m degenerate subspace", "authors": "Le Bin Ho", "venue": "Physical Review A 107, 042204 (2023)", "year": 2023, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.107.042204", "category": "foundations"},
    {"fy": 2023, "type": "peer", "title": "Universal compilation for quantum state tomography", "authors": "Vu Tuan Hai, Le Bin Ho", "venue": "Scientific Reports 13, 3750 (2023)", "year": 2023, "link": "https://www.nature.com/articles/s41598-023-30983-4", "category": "algorithms"},
    {"fy": 2023, "type": "peer", "title": "tqix.pis: a toolbox for quantum dynamics simulation of spin ensembles in Dicke basis", "authors": "Nguyen Tan Viet, Nguyen Thi Chuong, Vu Thi Ngoc Huyen, Le Bin Ho", "venue": "Computer Physics Communications 286, 108686 (2023)", "year": 2023, "link": "https://www.sciencedirect.com/science/article/pii/S0010465523000310", "category": "simulation"},
    {"fy": 2023, "type": "preprint", "title": "Variational preparation of entangled states on quantum computers", "authors": "Vu Tuan Hai, Nguyen Tan Viet, Le Bin Ho", "venue": "arXiv:2306.17422", "year": 2023, "link": "https://arxiv.org/abs/2306.17422", "category": "algorithms"},
    {"fy": 2022, "type": "peer", "title": "Error-disturbance uncertainty relations in Faraday measurements", "authors": "Le Bin Ho, Keiichi Edamatsu", "venue": "Physical Review A 105, 052228 (2022)", "year": 2022, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.105.052228", "category": "foundations"},
    {"fy": 2022, "type": "peer", "title": "Qsun: an open-source platform towards practical quantum machine learning applications", "authors": "Quoc Chuong Nguyen, Le Bin Ho, Lan Nguyen Tran, Hung Q. Nguyen", "venue": "Machine Learning: Science and Technology 3, 015034 (2022)", "year": 2022, "link": "https://iopscience.iop.org/article/10.1088/2632-2153/ac5997", "category": "algorithms"},
    {"fy": 2022, "type": "peer", "title": "Experimenting quantum phenomena on NISQ computers using high level quantum programming", "authors": "Duc M. Tran, Duy V. Nguyen, Le Bin Ho, Hung Q. Nguyen", "venue": "EPJ Quantum Technology 9, 6 (2022)", "year": 2022, "link": "https://epjquantumtechnology.springeropen.com/articles/10.1140/epjqt/s40507-022-00126-1", "category": "simulation"},
    {"fy": 2021, "type": "peer", "title": "tqix: a toolbox for quantum in X", "authors": "Le Bin Ho, Kieu Quang Tuan, Hung Q. Nguyen", "venue": "Computer Physics Communications 263, 107902 (2021)", "year": 2021, "link": "https://doi.org/10.1016/j.cpc.2021.107902", "category": "algorithms"},
    {"fy": 2021, "type": "peer", "title": "Direct state measurements under state-preparation-and-measurement errors", "authors": "Kieu Quang Tuan, Hung Q. Nguyen, Le Bin Ho", "venue": "Quantum Information Processing 20, 197 (2021)", "year": 2021, "link": "https://doi.org/10.1007/s11128-021-03144-7", "category": "foundations"},
    {"fy": 2021, "type": "peer", "title": "Multiparameter quantum metrology with postselection measurements", "authors": "Le Bin Ho, Yasushi Kondo", "venue": "Journal of Mathematical Physics 62, 012102 (2021)", "year": 2021, "link": "https://doi.org/10.1063/5.0024555", "category": "metrology"},
    {"fy": 2020, "type": "peer", "title": "Multiparameter quantum estimation under dephasing noise", "authors": "Le Bin Ho, Hideaki Hakoshima, Yuichiro Matsuzaki, Masayuki Matsuzaki, Yasushi Kondo", "venue": "Physical Review A 102, 022602 (2020)", "year": 2020, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.102.022602", "category": "metrology"},
    {"fy": 2020, "type": "peer", "title": "Systematic errors in direct state measurements with quantum controlled measurements", "authors": "Le Bin Ho", "venue": "Journal of Physics B: Atomic, Molecular and Optical Physics 53, 115501 (2020)", "year": 2020, "link": "https://doi.org/10.1088/1361-6455/ab7881", "category": "foundations"},
    {"fy": 2020, "type": "peer", "title": "Nuclear magnetic resonance model of an entangled sensor under noise", "authors": "Le Bin Ho, Yuichiro Matsuzaki, Masayuki Matsuzaki, Yasushi Kondo", "venue": "Journal of the Physical Society of Japan 89, 054001 (2020)", "year": 2020, "link": "https://doi.org/10.7566/JPSJ.89.054001", "category": "metrology"},
    {"fy": 2019, "type": "peer", "title": "Realization of controllable open system with NMR", "authors": "Le Bin Ho, Yuichiro Matsuzaki, Masayuki Matsuzaki, Yasushi Kondo", "venue": "New Journal of Physics 21, 093008 (2019)", "year": 2019, "link": "https://doi.org/10.1088/1367-2630/ab3a25", "category": "simulation"},
    {"fy": 2019, "type": "peer", "title": "Continuous-monitoring measured signals bounded by past and future conditions in enlarged quantum systems", "authors": "Le Bin Ho", "venue": "Quantum Information Processing 18, 206 (2019)", "year": 2019, "link": "https://doi.org/10.1007/s11128-019-2314-6", "category": "foundations"},
    {"fy": 2019, "type": "peer", "title": "Modular-value-based metrology with spin coherent pointers", "authors": "Le Bin Ho, Yasushi Kondo", "venue": "Physics Letters A 383, 153-157 (2019)", "year": 2019, "link": "https://doi.org/10.1016/j.physleta.2018.10.041", "category": "metrology"},
    {"fy": 2019, "type": "peer", "title": "Improving direct state measurements by using rebits in real enlarged Hilbert spaces", "authors": "Le Bin Ho", "venue": "Physics Letters A 383, 289-294 (2019)", "year": 2019, "link": "https://doi.org/10.1016/j.physleta.2018.10.047", "category": "foundations"},
    {"fy": 2018, "type": "peer", "title": "Various pointer states approaches to polar modular values", "authors": "Le Bin Ho, Nobuyuki Imoto", "venue": "Journal of Mathematical Physics 59, 042104 (2018)", "year": 2018, "category": "foundations"},
    {"fy": 2018, "type": "peer", "title": "Quantum weak and modular values in enlarged Hilbert spaces", "authors": "Le Bin Ho, Nobuyuki Imoto", "venue": "Physical Review A 97, 012112 (2018)", "year": 2018, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.97.012112", "category": "foundations"},
    {"fy": 2017, "type": "peer", "title": "Generalized modular-value-based scheme and its generalized modular value", "authors": "Le Bin Ho, Nobuyuki Imoto", "venue": "Physical Review A 95, 032135 (2017)", "year": 2017, "link": "https://journals.aps.org/pra/abstract/10.1103/PhysRevA.95.032135", "category": "foundations"},
    {"fy": 2016, "type": "peer", "title": "Photoenhanced spin/valley polarization and tunneling magnetoresistance in a ferromagnetic-normal-ferromagnetic silicene junction", "authors": "Le Bin Ho, Tran Nguyen Lan", "venue": "Journal of Physics D: Applied Physics 49 (2016)", "year": 2016, "link": "https://arxiv.org/abs/1605.02829", "category": None},
    {"fy": 2016, "type": "peer", "title": "Full characterization of modular values for finite-dimensional systems", "authors": "Le Bin Ho, Nobuyuki Imoto", "venue": "Physics Letters A 380, 2129-2135 (2016)", "year": 2016, "link": "https://doi.org/10.1016/j.physleta.2016.05.005", "category": "foundations"},
    {"fy": 2016, "type": "peer", "title": "Self-optimized biological channels in facilitating the transmembrane movement of charged molecules", "authors": "V. T. N. Huyen, Le Bin Ho, Vu Cong Lap, V. Lien Nguyen", "venue": "Journal of Biophysics 2016, 1657679 (2016)", "year": 2016, "link": "https://onlinelibrary.wiley.com/doi/10.1155/2016/1657679", "category": None},
    {"fy": 2014, "type": "peer", "title": "Electronic, magnetic, and spin-polarized transport properties of hybrid graphene/boron-nitride nanoribbons having 5-8-5 line defects at the heterojunction", "authors": "Tran Nguyen Lan, Le Bin Ho, Tran Hoang Hai", "venue": "Physica Status Solidi B 252, 3 (2014)", "year": 2014, "category": None},
    {"fy": 2013, "type": "peer", "title": "Monte Carlo simulations of core/shell nanoparticles containing interfacial defects: role of disordered ferromagnetic spins", "authors": "Le Bin Ho, Tran Nguyen Lan, Tran Hoang Hai", "venue": "Physica B: Condensed Matter 430 (2013)", "year": 2013, "category": None},
]
